name: Sign and Verify Image with Cosign

on:
  push:
    branches:
      - main

jobs:
  cosign:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Upstream: https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: chainguard-actions/sigstore-cosign-installer@3d4272fbfb966daf6ef8207d58530a6aa228bd45

      - name: Verify Cosign installation
        run: cosign version

  crane:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Upstream: https://github.com/imjasonh/setup-crane
      - name: Install Crane
        uses: chainguard-actions/imjasonh-setup-crane@1bdfdf057fc35a663d446c5e377af8a7e43a5c3d

      - name: Verify Crane installation
        run: crane version
